// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/controlled-model-fallback.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { guardProcessEnv } from "./helpers/env-guard.js";
guardProcessEnv();

/**
 * Reproducing regression tests for the controlled session model fallback policy.
 *
 * Run with:
 *   npx tsx --test --test-force-exit tests/controlled-model-fallback.test.ts
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, it } from "vitest";
import { fileURLToPath } from "node:url";

import {
	applyReviewModelOverrides,
	type ReviewModelRpc,
} from "../../src/server/agent/review-model-override.js";
import { applyRuntimeSessionModelSelection, broadcastRuntimeSessionActualModelState } from "../../src/server/ws/runtime-model-selection.js";
import { generateImage } from "../../src/server/agent/image-generation.js";
import { fallbackProviderAllowlistFromPrefs, resolveHostAgentProviderEnv } from "../../src/server/agent/host-tokens.js";
import { PreferencesStore } from "../../src/server/agent/preferences-store.js";
import { createMemFs } from "../harness/mem-fs.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..", "..");
const SESSION_MANAGER_SOURCE = path.join(PROJECT_ROOT, "src/server/agent/session-manager.ts");
const SESSION_SETUP_SOURCE = path.join(PROJECT_ROOT, "src/server/agent/session-setup.ts");
const SERVER_SOURCE = path.join(PROJECT_ROOT, "src/server/server.ts");
const WS_HANDLER_SOURCE = path.join(PROJECT_ROOT, "src/server/ws/handler.ts");

type Prefs = Record<string, unknown>;
type ModelPair = [string, string];

function extractRouteSlice(src: string, startMarker: string, endMarker: string): string {
	const start = src.indexOf(startMarker);
	assert.ok(start >= 0, `could not find ${startMarker}`);
	const end = src.indexOf(endMarker, start);
	assert.ok(end > start, `could not find ${endMarker} after ${startMarker}`);
	return src.slice(start, end);
}

function extractMethodBody(src: string, marker: string): string {
	const markerIndex = src.indexOf(marker);
	assert.ok(markerIndex >= 0, `could not find ${marker}`);
	const open = src.indexOf("{", markerIndex);
	assert.ok(open > markerIndex, `could not find opening brace for ${marker}`);
	let depth = 0;
	for (let i = open; i < src.length; i++) {
		const ch = src[i];
		if (ch === "{") depth++;
		if (ch === "}") depth--;
		if (depth === 0) return src.slice(open + 1, i);
	}
	throw new Error(`could not find closing brace for ${marker}`);
}

function loadTryAutoSelectModel(): (this: any, session: any) => Promise<void> {
	const src = readFileSync(SESSION_MANAGER_SOURCE, "utf-8");
	let body = extractMethodBody(src, "private async tryAutoSelectModel(session: SessionInfo)");
	body = body
		.replace(/\s+as\s+string\s*\|\s*undefined/g, "")
		.replace(/SessionManager\.AIGW_CACHE_TTL_MS/g, "60_000")
		// Strip TS-only syntax introduced by the multi-gateway fallback branch so the
		// method body parses under `new Function`: the inline `type` alias and its
		// annotation usage. Behavior is unchanged — these are erased at compile time.
		.replace(/\n\s*type\s+\w+\s*=\s*\{[^}]*\};/g, "")
		.replace(/:\s*GatewayCandidate\[\]/g, "");

	// The extracted production method now normalizes legacy provider-prefixed AIGW
	// preferences before selecting or comparing them. Keep that dependency explicit
	// in the eval harness and model one known migration; the normalizer itself has
	// exhaustive models.json-backed coverage in aigw-wellknown-translate.test.ts.
	const normalizeAigwModelString = (modelString: string) =>
		modelString === "aigw/openai/legacy-model" ? "aigw/legacy-model" : modelString;
	const applyModelString = async (rpc: any, modelString: string, opts: any = {}) => {
		const slash = modelString.indexOf("/");
		if (slash <= 0 || slash >= modelString.length - 1) {
			throw new Error(`malformed ${opts.contextLabel ?? "model"}: ${modelString}`);
		}
		const provider = modelString.slice(0, slash);
		const modelId = modelString.slice(slash + 1);
		if (!opts.skipSetModel) await rpc.setModel(provider, modelId);
		const state = await rpc.getState();
		const bound = state?.data?.model ?? state?.model;
		if (bound?.provider !== provider || bound?.id !== modelId) {
			throw new Error(`setModel read-back mismatch for ${modelString}`);
		}
	};
	const isSessionSelectableModelString = (value: unknown) => (
		typeof value === "string" && /^[^/]+\/.+/.test(value) && !value.startsWith("image-only/")
	);
	// Multi-gateway migration: the fallback branch now enumerates configured
	// gateways instead of a single `aigw.baseUrl`. Mirror the prior stubs — a
	// gateway IS available (derived from the same `aigw.baseUrl` pref the tests set)
	// and discovery yields a model — so the "never falls through to the gateway"
	// assertions still prove the controlled policy suppresses gateway auto-selection
	// after an explicit-model failure.
	const listGateways = (prefs: { get: (key: string) => unknown }) => {
		const url = prefs.get("aigw.baseUrl");
		return typeof url === "string" && url
			? [{ id: "aigw", name: "aigw", url, type: "aigw", enabled: true }]
			: [];
	};
	const getEnabledGateways = (prefs: { get: (key: string) => unknown }) => listGateways(prefs).filter((g: any) => g.enabled);
	const isExclusiveMode = (gateways: any[]) => gateways.some((g) => g.enabled && g.type === "aigw");
	const bedrockRoutesForType = (type: string) => type === "aigw";
	const isClaudeId = (id: string) => /claude/i.test(id);
	const stripProviderPrefix = (id: string) => (id.includes("/") ? id.slice(id.indexOf("/") + 1) : id);
	const modelRecencyRank = () => 1;
	const inferMeta = () => ({ reasoning: false });
	const sanitizeModelErrorText = (err: unknown) => err instanceof Error ? err.message : String(err);
	const sanitizeModelErrorForLog = sanitizeModelErrorText;
	const broadcast = (clients: Set<any>, message: any) => {
		for (const client of clients) client.messages.push(message);
	};
	// Stub for the module-level helper `tryAutoSelectModel` uses to build the
	// `state` broadcast payload from the registry-backed resolver
	// (`resolveModelStateMeta`). The eval scope has no model-registry cache, so
	// mirror only the shape the assertions read (`data.model.{provider,id}`).
	const buildModelStateData = (provider: string, id: string) => ({
		model: { provider, id, reasoning: false },
	});

	// eslint-disable-next-line no-new-func
	return new Function(
		"normalizeAigwModelString",
		"applyModelString",
		"isSessionSelectableModelString",
		"listGateways",
		"getEnabledGateways",
		"isExclusiveMode",
		"bedrockRoutesForType",
		"isClaudeId",
		"stripProviderPrefix",
		"modelRecencyRank",
		"inferMeta",
		"sanitizeModelErrorText",
		"sanitizeModelErrorForLog",
		"broadcast",
		"buildModelStateData",
		`return async function tryAutoSelectModel(session) {${body}\n};`,
	)(
		normalizeAigwModelString,
		applyModelString,
		isSessionSelectableModelString,
		listGateways,
		getEnabledGateways,
		isExclusiveMode,
		bedrockRoutesForType,
		isClaudeId,
		stripProviderPrefix,
		modelRecencyRank,
		inferMeta,
		sanitizeModelErrorText,
		sanitizeModelErrorForLog,
		broadcast,
		buildModelStateData,
	);
}

const tryAutoSelectModel = loadTryAutoSelectModel();

async function exerciseAutoSelect(options: {
	prefs: Prefs;
	roleModel?: string;
	failModels?: string[];
	spawnPinnedModel?: string;
	initialBound?: { provider: string; id: string };
}): Promise<{
	error: unknown;
	setModelCalls: ModelPair[];
	persisted: Array<Record<string, unknown>>;
	modelFiles: string[];
	broadcastModels: Array<{ provider: string; id: string }>;
}> {
	const setModelCalls: ModelPair[] = [];
	const persisted: Array<Record<string, unknown>> = [];
	const modelFiles: string[] = [];
	let bound: { provider: string; id: string } | undefined = options.initialBound;
	const failModels = new Set(options.failModels ?? []);
	const client = { messages: [] as any[] };
	const manager = {
		preferencesStore: { get: (key: string) => options.prefs[key] },
		resolveRoleModel: () => options.roleModel,
		resolveStoreForSession: () => ({
			update: (_sessionId: string, update: Record<string, unknown>) => persisted.push(update),
		}),
		_writeModelNameFile: (_sessionId: string, model: string) => modelFiles.push(model),
		_gatewayModelCache: new Map<string, { url: string; models: unknown[]; ts: number }>(),
		// Mirrors the old `discoverAigwModels` stub: a gateway model is available so
		// the auto-selection branch has something to (deliberately) NOT pick.
		discoverGatewayModelsCached: async () => ([{ id: "us.anthropic.claude-opus-4-5" }]),
	};
	const session = {
		id: "session-under-test",
		role: "coder",
		spawnPinnedModel: options.spawnPinnedModel,
		clients: new Set([client]),
		rpcClient: {
			async setModel(provider: string, modelId: string) {
				setModelCalls.push([provider, modelId]);
				const key = `${provider}/${modelId}`;
				if (failModels.has(key)) {
					throw new Error(`controlled model fallback policy fixture: unavailable ${key}`);
				}
				bound = { provider, id: modelId };
			},
			async getState() {
				return { model: bound ?? { provider: "unset", id: "unset" } };
			},
		},
	};

	let error: unknown;
	try {
		await tryAutoSelectModel.call(manager, session);
	} catch (err) {
		error = err;
	}

	return {
		error,
		setModelCalls,
		persisted,
		modelFiles,
		broadcastModels: client.messages
			.map((msg) => msg?.data?.model)
			.filter(Boolean)
			.map((model) => ({ provider: model.provider, id: model.id })),
	};
}

function makeReviewRpc(failModels: string[] = []): ReviewModelRpc & {
	setModelCalls: ModelPair[];
	persistedModel?: { provider: string; id: string };
} {
	const setModelCalls: ModelPair[] = [];
	const fail = new Set(failModels);
	let bound: { provider: string; id: string } | undefined;
	return {
		setModelCalls,
		async setModel(provider: string, modelId: string) {
			setModelCalls.push([provider, modelId]);
			const key = `${provider}/${modelId}`;
			if (fail.has(key)) throw new Error(`controlled model fallback policy fixture: unavailable ${key}`);
			bound = { provider, id: modelId };
		},
		async getState() {
			return { model: bound ?? { provider: "unset", id: "unset" } };
		},
	} as any;
}

function makeRuntimeHarness(options: {
	prefs?: Prefs;
	failModels?: string[];
	readBack?: { provider: string; id: string };
	readBackSequence?: Array<{ provider: string; id: string }>;
} = {}) {
	const setModelCalls: ModelPair[] = [];
	const persisted: Array<{ sessionId: string; provider: string; modelId: string }> = [];
	const modelFiles: string[] = [];
	const messages: any[] = [];
	let bound: { provider: string; id: string } | undefined;
	const readBackSequence = [...(options.readBackSequence ?? [])];
	const fail = new Set(options.failModels ?? []);
	const sessionManager = {
		persistSessionModel(sessionId: string, provider: string, modelId: string) {
			persisted.push({ sessionId, provider, modelId });
		},
		getPersistedSession(sessionId: string) {
			const match = [...persisted].reverse().find((entry) => entry.sessionId === sessionId);
			return match ? { modelProvider: match.provider, modelId: match.modelId } : undefined;
		},
		updateModelNameFile(_sessionId: string, modelName: string) {
			modelFiles.push(modelName);
		},
	};
	const session = {
		id: "runtime-session",
		clients: new Set([{ readyState: 1, send: (raw: string) => messages.push(JSON.parse(raw)) }]),
		rpcClient: {
			async setModel(provider: string, modelId: string) {
				setModelCalls.push([provider, modelId]);
				const key = `${provider}/${modelId}`;
				if (fail.has(key)) throw new Error(`controlled model fallback policy fixture: unavailable ${key}`);
				bound = { provider, id: modelId };
			},
			async getState() {
				return { model: readBackSequence.shift() ?? options.readBack ?? bound ?? { provider: "unset", id: "unset" } };
			},
		},
	};
	const prefs = {
		get(key: string) {
			return options.prefs?.[key];
		},
	};
	const broadcast = (_clients: any, msg: any) => messages.push(msg);
	return { sessionManager, session, prefs, broadcast, setModelCalls, persisted, modelFiles, messages };
}

function tempPrefs(): { prefs: PreferencesStore; cleanup: () => void } {
	const memfs = createMemFs();
	const dir = path.resolve("/memfs/controlled-fallback");
	return {
		prefs: new PreferencesStore(dir, memfs),
		cleanup: () => memfs.rmSync(dir, { recursive: true, force: true }),
	};
}

describe("controlled model fallback policy — session auto-selection", () => {
	it("off/absent setting: failing explicit default.sessionModel rejects and never falls through to AIGW", async () => {
		const result = await exerciseAutoSelect({
			prefs: {
				"default.sessionModel": "aigw/dead-default",
				"aigw.baseUrl": "https://aigw.test",
			},
			failModels: ["aigw/dead-default"],
		});

		assert.ok(
			result.error,
			"controlled model fallback policy: failing explicit default.sessionModel must reject instead of selecting AIGW best-ranked",
		);
		assert.deepEqual(
			result.setModelCalls,
			[["aigw", "dead-default"]],
			"controlled model fallback policy: no AIGW best-ranked setModel call is allowed after explicit default.sessionModel fails",
		);
		assert.equal(result.persisted.length, 0, "controlled model fallback policy: failed explicit model must not persist another model");
		assert.equal(result.modelFiles.length, 0, "controlled model fallback policy: failed explicit model must not write a fallback .model file");
		assert.equal(result.broadcastModels.length, 0, "controlled model fallback policy: failed explicit model must not broadcast a fallback model");
	});

	it("enabled setting: failing explicit role model falls back exactly once to default.sessionModel and persists the actual fallback", async () => {
		const result = await exerciseAutoSelect({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "openai/fallback-session",
				"aigw.baseUrl": "https://aigw.test",
			},
			roleModel: "anthropic/dead-role",
			failModels: ["anthropic/dead-role"],
		});

		assert.equal(result.error, undefined, "controlled model fallback policy: enabled setting should allow role model to fall back to default.sessionModel");
		assert.deepEqual(
			result.setModelCalls,
			[["anthropic", "dead-role"], ["openai", "fallback-session"]],
			"controlled model fallback policy: role fallback may try only the selected model and default.sessionModel",
		);
		assert.deepEqual(
			result.persisted,
			[{ modelProvider: "openai", modelId: "fallback-session" }],
			"controlled model fallback policy: persisted model must be the actual default.sessionModel fallback",
		);
		assert.deepEqual(result.broadcastModels, [{ provider: "openai", id: "fallback-session" }]);
		assert.deepEqual(result.modelFiles, ["openai/fallback-session"]);
	});

	it("normalizes a legacy provider-prefixed AIGW default before selecting and persisting it", async () => {
		const result = await exerciseAutoSelect({
			prefs: { "default.sessionModel": "aigw/openai/legacy-model" },
		});

		assert.equal(result.error, undefined);
		assert.deepEqual(result.setModelCalls, [["aigw", "legacy-model"]]);
		assert.deepEqual(result.persisted, [{ modelProvider: "aigw", modelId: "legacy-model" }]);
		assert.deepEqual(result.modelFiles, ["aigw/legacy-model"]);
		assert.deepEqual(result.broadcastModels, [{ provider: "aigw", id: "legacy-model" }]);
	});

	it("enabled setting: malformed explicit default.sessionModel fails loudly and never chooses AIGW/hardcoded fallback", async () => {
		const result = await exerciseAutoSelect({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "not-a-model-pref",
				"aigw.baseUrl": "https://aigw.test",
			},
		});

		assert.ok(result.error, "controlled model fallback policy: malformed explicit default.sessionModel must reject");
		assert.deepEqual(result.setModelCalls, [], "controlled model fallback policy: malformed default.sessionModel must not trigger AIGW/hardcoded setModel");
		assert.equal(result.persisted.length, 0, "controlled model fallback policy: malformed default.sessionModel must not persist a fallback");
	});

	it("enabled setting: missing, same-as-selected, or failing default.sessionModel never falls through to AIGW", async () => {
		const missing = await exerciseAutoSelect({
			prefs: { allowSessionModelFallback: true, "aigw.baseUrl": "https://aigw.test" },
			roleModel: "anthropic/dead-role",
			failModels: ["anthropic/dead-role"],
		});
		assert.ok(missing.error, "controlled model fallback policy: missing default.sessionModel must reject");
		assert.deepEqual(missing.setModelCalls, [["anthropic", "dead-role"]]);
		assert.equal(missing.persisted.length, 0);

		const same = await exerciseAutoSelect({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "anthropic/dead-role",
				"aigw.baseUrl": "https://aigw.test",
			},
			roleModel: "anthropic/dead-role",
			failModels: ["anthropic/dead-role"],
		});
		assert.ok(same.error, "controlled model fallback policy: same-as-selected default.sessionModel must reject");
		assert.deepEqual(same.setModelCalls, [["anthropic", "dead-role"]]);
		assert.equal(same.persisted.length, 0);

		const failingDefault = await exerciseAutoSelect({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "openai/dead-fallback",
				"aigw.baseUrl": "https://aigw.test",
			},
			roleModel: "anthropic/dead-role",
			failModels: ["anthropic/dead-role", "openai/dead-fallback"],
		});
		assert.ok(failingDefault.error, "controlled model fallback policy: failing default.sessionModel fallback must reject");
		assert.deepEqual(
			failingDefault.setModelCalls,
			[["anthropic", "dead-role"], ["openai", "dead-fallback"]],
			"controlled model fallback policy: failing fallback target should be tried exactly once, then stop without AIGW",
		);
		assert.equal(failingDefault.persisted.length, 0);
	});

	it("restore/respawn spawn-pinned model is verified and fails visibly when fallback is off", async () => {
		const result = await exerciseAutoSelect({
			prefs: { "aigw.baseUrl": "https://aigw.test" },
			spawnPinnedModel: "anthropic/stale-persisted",
			initialBound: { provider: "unset", id: "unset" },
		});

		assert.ok(result.error, "controlled model fallback policy: stale spawn-pinned persisted model must fail when fallback is off");
		assert.deepEqual(result.setModelCalls, [], "spawn-pinned verification must not call setModel for the failed selected model or AIGW");
		assert.equal(result.persisted.length, 0);
		assert.equal(result.broadcastModels.length, 0);
	});

	it("enabled setting: failing restore/respawn spawn-pinned model falls back only to default.sessionModel", async () => {
		const result = await exerciseAutoSelect({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "openai/fallback-session",
				"aigw.baseUrl": "https://aigw.test",
			},
			spawnPinnedModel: "anthropic/stale-persisted",
			initialBound: { provider: "unset", id: "unset" },
		});

		assert.equal(result.error, undefined);
		assert.deepEqual(result.setModelCalls, [["openai", "fallback-session"]]);
		assert.deepEqual(result.persisted, [{ modelProvider: "openai", modelId: "fallback-session" }]);
		assert.deepEqual(result.broadcastModels, [{ provider: "openai", id: "fallback-session" }]);
	});
});

describe("controlled model fallback policy — runtime WS set_model", () => {
	it("fallback off: delayed read-back settle succeeds, persists, and broadcasts selected model", async () => {
		const harness = makeRuntimeHarness({
			readBackSequence: [
				{ provider: "anthropic", id: "old-model" },
				{ provider: "anthropic", id: "selected-new" },
			],
		});

		const actual = await applyRuntimeSessionModelSelection(
			harness.sessionManager as any,
			harness.session as any,
			"anthropic",
			"selected-new",
			harness.prefs as any,
			harness.broadcast,
		);

		assert.deepEqual(actual, { provider: "anthropic", id: "selected-new" });
		assert.deepEqual(harness.setModelCalls, [["anthropic", "selected-new"]]);
		assert.deepEqual(harness.persisted, [{ sessionId: "runtime-session", provider: "anthropic", modelId: "selected-new" }]);
		assert.deepEqual(harness.modelFiles, ["anthropic/selected-new"]);
		assert.deepEqual(harness.messages.map((msg) => msg?.data?.model?.provider), ["anthropic"]);
		assert.deepEqual(harness.messages.map((msg) => msg?.data?.model?.id), ["selected-new"]);
	});

	it("fallback off: read-back mismatch rejects and does not persist, broadcast, or update model file", async () => {
		const harness = makeRuntimeHarness({
			readBack: { provider: "anthropic", id: "still-old" },
		});

		await assert.rejects(
			applyRuntimeSessionModelSelection(
				harness.sessionManager as any,
				harness.session as any,
				"anthropic",
				"selected-new",
				harness.prefs as any,
				harness.broadcast,
			),
			/read-back mismatch|mismatch/i,
		);

		assert.deepEqual(harness.setModelCalls, [["anthropic", "selected-new"]]);
		assert.deepEqual(harness.persisted, [], "runtime set_model mismatch must not persist the selected model");
		assert.deepEqual(harness.modelFiles, [], "runtime set_model mismatch must not update .model state");
		assert.deepEqual(harness.messages, [], "runtime set_model mismatch must not broadcast a successful model state");
	});

	it("fallback off: failed set_model reconciliation broadcasts the actual RPC-bound model", async () => {
		const harness = makeRuntimeHarness({
			readBack: { provider: "anthropic", id: "still-old" },
		});

		await assert.rejects(
			applyRuntimeSessionModelSelection(
				harness.sessionManager as any,
				harness.session as any,
				"anthropic",
				"selected-new",
				harness.prefs as any,
				harness.broadcast,
			),
			/read-back mismatch|mismatch/i,
		);
		const actual = await broadcastRuntimeSessionActualModelState(
			harness.sessionManager as any,
			harness.session as any,
			harness.broadcast,
		);

		assert.deepEqual(actual, { provider: "anthropic", id: "still-old" });
		assert.deepEqual(harness.persisted, [], "reconciliation must not persist the rejected selected model");
		assert.deepEqual(harness.modelFiles, [], "reconciliation must not update .model state");
		assert.deepEqual(harness.messages.map((msg) => msg?.data?.model?.provider), ["anthropic"]);
		assert.deepEqual(harness.messages.map((msg) => msg?.data?.model?.id), ["still-old"]);
	});

	it("fallback on: failed non-default runtime selection falls back only to default.sessionModel and displays that actual model", async () => {
		const harness = makeRuntimeHarness({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "openai/fallback-session",
			},
			failModels: ["anthropic/dead-selected"],
		});

		const actual = await applyRuntimeSessionModelSelection(
			harness.sessionManager as any,
			harness.session as any,
			"anthropic",
			"dead-selected",
			harness.prefs as any,
			harness.broadcast,
		);

		assert.deepEqual(actual, { provider: "openai", id: "fallback-session" });
		assert.deepEqual(harness.setModelCalls, [["anthropic", "dead-selected"], ["openai", "fallback-session"]]);
		assert.deepEqual(harness.persisted, [{ sessionId: "runtime-session", provider: "openai", modelId: "fallback-session" }]);
		assert.deepEqual(harness.modelFiles, ["openai/fallback-session"]);
		assert.deepEqual(harness.messages.map((msg) => msg?.data?.model?.provider), ["openai"]);
		assert.deepEqual(harness.messages.map((msg) => msg?.data?.model?.id), ["fallback-session"]);
	});

	it("fallback on: same-as-selected default.sessionModel rejects without trying another fallback or persisting stale state", async () => {
		const harness = makeRuntimeHarness({
			prefs: {
				allowSessionModelFallback: true,
				"default.sessionModel": "anthropic/dead-selected",
			},
			failModels: ["anthropic/dead-selected"],
		});

		await assert.rejects(
			applyRuntimeSessionModelSelection(
				harness.sessionManager as any,
				harness.session as any,
				"anthropic",
				"dead-selected",
				harness.prefs as any,
				harness.broadcast,
			),
			/same as failed model|fallback rejected/i,
		);

		assert.deepEqual(harness.setModelCalls, [["anthropic", "dead-selected"]]);
		assert.deepEqual(harness.persisted, []);
		assert.deepEqual(harness.modelFiles, []);
	});

	it("handler emits authoritative state before SET_MODEL_FAILED on runtime set_model failure", () => {
		const src = readFileSync(WS_HANDLER_SOURCE, "utf-8");
		const setModelCase = extractRouteSlice(src, 'case "set_model":', 'case "set_image_model":');
		const reconcileIdx = setModelCase.indexOf("await broadcastRuntimeSessionActualModelState(sessionManager, session, broadcast)");
		const errorIdx = setModelCase.indexOf("SET_MODEL_FAILED");
		assert.ok(reconcileIdx >= 0, "set_model failure must broadcast the authoritative actual model");
		assert.ok(errorIdx > reconcileIdx, "SET_MODEL_FAILED should be sent after the corrective model state frame");
	});
});

describe("controlled model fallback policy — session setup visibility", () => {
	it("normal/worktree post-spawn model selection is awaited, not swallowed as a warning", () => {
		const src = readFileSync(SESSION_SETUP_SOURCE, "utf-8");
		const postSpawnBody = extractMethodBody(src, "async function postSpawn(session: SessionInfo");

		assert.match(
			postSpawnBody,
			/await\s+ctx\.tryAutoSelectModel\(session\)/,
			"controlled model fallback policy: post-spawn model selection must be awaited so explicit failures reject visibly",
		);
		assert.doesNotMatch(
			postSpawnBody,
			/tryAutoSelectModel\(session\)\.catch[\s\S]*Early model selection failed/,
			"controlled model fallback policy: model selection failures must not be swallowed as fire-and-forget warnings",
		);
		assert.match(
			postSpawnBody,
			/tryApplyDefaultThinkingLevel\(session\)\.catch[\s\S]*Early thinking level failed/,
			"thinking-level failures may remain non-fatal warnings",
		);

		const worktreeBody = extractMethodBody(src, "export async function executeWorktreeAsync");
		const postSpawnIdx = worktreeBody.indexOf("await postSpawn(session, plan, ctx)");
		const idleIdx = worktreeBody.indexOf('broadcastStatus(session, "idle")');
		assert.ok(postSpawnIdx >= 0, "worktree setup must call postSpawn");
		assert.ok(idleIdx >= 0, "worktree setup must broadcast idle");
		assert.ok(
			postSpawnIdx < idleIdx,
			"controlled model fallback policy: worktree sessions must enforce model selection before becoming idle/live",
		);
	});
});

describe("controlled model fallback policy — restore/respawn lifecycle", () => {
	it("fork and continue routes verify inherited persisted models instead of skipping auto-selection", () => {
		const src = readFileSync(SERVER_SOURCE, "utf-8");
		const forkRoute = extractRouteSlice(src, "// POST /api/sessions/:id/fork", "// POST /api/sessions/:id/wait");
		const continueRoute = extractRouteSlice(src, "// POST /api/sessions/:archivedId/continue", "// GET /api/sessions/:id/output");

		for (const [label, route] of [["fork", forkRoute], ["continue", continueRoute]] as const) {
			assert.match(
				route,
				/if \(ps\.modelProvider && ps\.modelId\)[\s\S]*createOpts\.initialModel = `\$\{ps\.modelProvider\}\/\$\{ps\.modelId\}`/,
				`${label}: persisted model should still be spawn-pinned as the explicit selected model`,
			);
			assert.doesNotMatch(
				route,
				/skipAutoModel:\s*!!\(ps\.modelProvider && ps\.modelId\)/,
				`${label}: inherited explicit model must not bypass post-spawn read-back/fallback enforcement`,
			);
			assert.doesNotMatch(
				route,
				/persistSessionModel\([^,]+,\s*ps\.modelProvider,\s*ps\.modelId\)/,
				`${label}: route must not re-persist a stale inherited model after controlled fallback may have selected another model`,
			);
		}
	});

	it("restore verifies spawn-pinned persisted model before broadcasting idle", () => {
		const src = readFileSync(SESSION_MANAGER_SOURCE, "utf-8");
		const body = extractMethodBody(src, "private async restoreSession(ps: PersistedSession)");

		assert.match(
			body,
			/spawnPinnedModel:\s*bridgeOptions\.initialModel/,
			"controlled model fallback policy: restored persisted initialModel must be carried as spawnPinnedModel for read-back verification",
		);
		const switchIdx = body.indexOf("if (!switchResp.success)");
		const verifyIdx = body.indexOf("await this.tryAutoSelectModel(session)");
		const idleIdx = body.indexOf('broadcastStatus(session, "idle")', verifyIdx);
		assert.ok(switchIdx >= 0 && verifyIdx > switchIdx, "restore must verify model after switch_session succeeds");
		assert.ok(idleIdx > verifyIdx, "restore must verify controlled fallback policy before broadcasting idle");
	});

	it("role assignment and force-abort respawns verify spawn-pinned model before idle", () => {
		const src = readFileSync(SESSION_MANAGER_SOURCE, "utf-8");

		// Role assignment now stages and verifies a replacement before committing it.
		// The shared coordinator broadcasts idle only after the staged operation
		// resolves, so pin/verify/commit and operation/idle ordering are separate
		// source-level invariants rather than one contiguous method-body sequence.
		const roleBody = extractMethodBody(src, "token: SessionReplacementToken,\n\t): Promise<boolean> {");
		const stagedPinnedIdx = roleBody.indexOf("spawnPinnedModel: bridgeOptions.initialModel");
		const stagedVerifyIdx = roleBody.indexOf("await this.tryAutoSelectModel(stagedSession)", stagedPinnedIdx);
		const roleCommitIdx = roleBody.indexOf("session.spawnPinnedModel = bridgeOptions.initialModel", stagedVerifyIdx);
		assert.ok(stagedPinnedIdx >= 0, "role assignment: staged respawn must carry initialModel as spawnPinnedModel");
		assert.ok(stagedVerifyIdx > stagedPinnedIdx, "role assignment: staged respawn must verify spawn-pinned model");
		assert.ok(roleCommitIdx > stagedVerifyIdx, "role assignment: verified model must precede replacement commit");

		const coordinatorBody = extractMethodBody(src, "): Promise<T> {\n\t\tlet coordinator = this._sessionReplacementCoordinators.get(sessionId);");
		const operationIdx = coordinatorBody.indexOf("const result = await operation(token)");
		const coordinatorIdleIdx = coordinatorBody.indexOf('broadcastStatus(canonical, "idle")', operationIdx);
		assert.ok(operationIdx >= 0, "role assignment: coordinator must await staged replacement");
		assert.ok(coordinatorIdleIdx > operationIdx, "role assignment: coordinator must not broadcast idle before verification completes");

		const forceBody = extractMethodBody(src, "private async _forceAbortOwned(");
		const forcePinnedIdx = forceBody.indexOf("session.spawnPinnedModel = bridgeOptions.initialModel");
		const forceVerifyIdx = forceBody.indexOf("await this.tryAutoSelectModel(session)", forcePinnedIdx);
		const forceIdleIdx = forceBody.indexOf('broadcastStatus(session, "idle")', forceVerifyIdx);
		assert.ok(forcePinnedIdx >= 0, "force abort: respawn must carry initialModel as spawnPinnedModel");
		assert.ok(forceVerifyIdx > forcePinnedIdx, "force abort: respawn must verify spawn-pinned model");
		assert.ok(forceIdleIdx > forceVerifyIdx, "force abort: respawn must verify model before broadcasting idle");
	});
});

describe("controlled model fallback policy — direct host provider env", () => {
	it("includes fallback provider credentials only when controlled fallback is enabled", () => {
		const makePrefs = (allow: boolean) => ({
			get(key: string) {
				return ({
					allowSessionModelFallback: allow,
					"default.sessionModel": "openai/fallback-session",
					"providerKey.anthropic": "anthropic-key",
					"providerKey.openai": "openai-key",
					"providerKey.xai": "xai-key",
				} as Record<string, unknown>)[key];
			},
		});

		const enabledPrefs = makePrefs(true);
		assert.deepEqual(
			resolveHostAgentProviderEnv(enabledPrefs as any, {
				model: "anthropic/selected-session",
				providers: fallbackProviderAllowlistFromPrefs(enabledPrefs as any),
			}),
			{ ANTHROPIC_API_KEY: "anthropic-key", OPENAI_API_KEY: "openai-key" },
			"enabled policy must allow credentials for selected provider and default.sessionModel fallback provider only",
		);

		const disabledPrefs = makePrefs(false);
		assert.deepEqual(
			resolveHostAgentProviderEnv(disabledPrefs as any, {
				model: "anthropic/selected-session",
				providers: fallbackProviderAllowlistFromPrefs(disabledPrefs as any),
			}),
			{ ANTHROPIC_API_KEY: "anthropic-key" },
			"disabled policy must not inject fallback provider credentials",
		);
	});

	it("normal setup and restore/respawn use the fallback provider allowlist", () => {
		const setupSrc = readFileSync(SESSION_SETUP_SOURCE, "utf-8");
		const managerSrc = readFileSync(SESSION_MANAGER_SOURCE, "utf-8");

		assert.match(setupSrc, /providers:\s*fallbackProviderAllowlistFromPrefs\(ctx\.preferencesStore\)/);
		assert.match(managerSrc, /providers:\s*fallbackProviderAllowlistFromPrefs\(this\.preferencesStore\)/);
	});
});

describe("controlled model fallback policy — review model overrides", () => {
	it("enabled setting: failing explicit review model falls back only to default.sessionModel and persists that actual model", async () => {
		const rpc = makeReviewRpc(["aigw/dead-review"]);
		const persisted: Array<{ sessionId: string; provider: string; modelId: string }> = [];
		const prefs = {
			get(key: string) {
				return ({
					allowSessionModelFallback: true,
					"default.reviewModel": "aigw/dead-review",
					"default.sessionModel": "openai/fallback-session",
				} as Record<string, unknown>)[key] as string | undefined;
			},
		};

		await applyReviewModelOverrides(rpc, {
			prefs,
			sessionId: "review-session",
			sessionManager: {
				persistSessionModel(sessionId: string, provider: string, modelId: string) {
					persisted.push({ sessionId, provider, modelId });
				},
			},
			maxAttempts: 1,
			retryDelayMs: 0,
			controlledFallback: { enabled: true, model: "openai/fallback-session" },
		} as any);

		assert.deepEqual(
			rpc.setModelCalls,
			[["aigw", "dead-review"], ["openai", "fallback-session"]],
			"controlled model fallback policy: review fallback may try only the selected review model and default.sessionModel",
		);
		assert.deepEqual(
			persisted,
			[{ sessionId: "review-session", provider: "openai", modelId: "fallback-session" }],
			"controlled model fallback policy: review fallback must persist/display the actual default.sessionModel fallback",
		);
	});
});

describe("controlled model fallback policy — image generation remains separate", () => {
	it("explicit unavailable image model does not benefit from session fallback setting", async () => {
		const { prefs, cleanup } = tempPrefs();
		const previousFetch = globalThis.fetch;
		let fetchCalls = 0;
		try {
			prefs.set("allowSessionModelFallback", true as any);
			prefs.set("default.sessionModel", "openai/fallback-session");
			prefs.set("providerKey.openai", "test-openai-key");
			globalThis.fetch = (async () => {
				fetchCalls++;
				throw new Error("controlled model fallback policy: explicit image model fell through to a fallback image request");
			}) as typeof fetch;

			let error: unknown;
			try {
				await generateImage(prefs, { prompt: "test", model: "not-a-provider/not-an-image-model" });
			} catch (err) {
				error = err;
			}

			assert.ok(error, "controlled model fallback policy: explicit unavailable image model must fail loudly");
			assert.match(
				String((error as Error).message ?? error),
				/unknown|unavailable|unsupported|not configured|controlled model fallback policy/i,
				"controlled model fallback policy: image failure should identify unavailable explicit image model",
			);
			assert.equal(fetchCalls, 0, "controlled model fallback policy: image generation must not use fallback/default image model after explicit image selection fails");
		} finally {
			globalThis.fetch = previousFetch;
			cleanup();
		}
	});
});
